Module8 task1
htmlacademy-ecmascript/1146763-cinemaddict-12 pull request #10
Opened 2020-08-31 09:22 UTC by DEADushka108

2020-09-01 07:35 UTC, Shv-sergey70 requested changes
Пока нужно внести правки по тому что я написал в комментариях. В основном нужно реализовать правильную логику презентеров (через контейнеры)

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/utils/filter.js
> +export const getWatchedFilms = (films) => films.filter((film) => film.isInHistory);
Экспорт нужно делать в конце файла
https://up.htmlacademy.ru/ecmascript/12/criteries#b14

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/utils/filter.js
>  export const getFiltredFilms = (films, filterType) => {
`getFiltredFilms` опечатка

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/main.js
> +filterPresenter.render();
Всегда, если экземпляр класса вызывает только один метод и больше не используется - то незачем его сохранять в переменную. Можно сразу вызывать нужный метод:
`new FilterPresenter(mainNavigation, filmsModel).render();`

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +    this._filmsList = document.querySelector(`.films-list`);
Так делать не стоит. В презентере нельзя искать элементы обращаясь в документу. Нужно передавать в конструктор контейнер, с которым может работать презентер. Внутри него можно искать элементы через `querySelector`, но никак не через `document`

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +    this._filmsList = null;
А эту переменную ты как-то используешь? Я вижу что в нее ты делаешь запись, но применения не нашел

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +  constructor(filmsModel, commentsModel, api) {
Где контейнер презентера?

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +    const previouseCardCount = this._currentCardsCount;
`previouseCardCount`  - опечатка

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/components/user-title.js
> +  constructor(films) {
В идеале сюда НЕ передавать фильмы, а сразу ранг пользователя

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/models/comments.js
> +    return true;
А разве может быть не `true`? Зачем вообще булево возвращать значение?

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/components/filter.js
> +    this._currenFilterType = FilterType.ALL;
Вообще эта переменная нужна?

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/components/filter.js
> +         id="${MenuItem.FILMS}"
У всех одинаковый ID? Это не хорошо

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/components/filter.js
> +    const {address, name, count, checked} = filter;
`checked` - обычно если там булево, то пишется так  `isChecked`

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/presenter/filter.js
> +    });
```
const filters = Object.values(FilterType).map((filterType) => ({
      name: filterType,
      count: getFiltredFilms(allFilms, filterType).length,
      address: filterType.replace(/\s+/g, ``).trim().toLowerCase(),
      checked: filterType === this._activeFilterType,
    }));
```

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/presenter/filter.js
> +    });
И вынеси это в приватный метод

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/presenter/filter.js
> +    const container = this._container;
А зачем эта переменная, можно же сразу использовать через this на 39 строчке:
`render(this._container, this._filterComponent, RenderPosition.AFTERBEGIN);`

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/components/film-card.js
>    const DescriptionLenght = {
Опечатка `length`

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/components/film-card.js
>      this.getElement().querySelector(`.film-card__comments`).addEventListener(`click`, callback);
Можно так, найдя все элементы за один обход дом-дерева:
```
this.getElement()
      .querySelectorAll(`.film-card__poster, .film-card__title, .film-card__comments`)
      .forEach((element) => element.addEventListener(`click`, callback));
```

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/components/film-details.js
> +export default class FilmDetails extends AbstractSmartComponent {
Чем этот компонент отличается от `FilmPopup`?

2020-09-01 07:35 UTC, Shv-sergey70 commented on src/models/comments.js
> +  }
Этот метод нигде не используется?
P.S. Такого свойства `this._dataChangeHandler` - нет. Есть `this._dataChangeHandlers`

2020-09-01 07:48 UTC, DEADushka108 commented on src/components/film-details-controls.js
> +    return createFilmDetailsTemplate(this._film, this._comments);
Рудимент

2020-09-01 08:26 UTC, DEADushka108 commented on src/components/film-list-container.js
> +export default class FilmListContainer extends AbstractComponent {
я его добавляю только когда есть данные с фильмами, когда их нет там просто стоят заглушки с Loading... и there are no films in our database. Что бы не было лишних элементов в разметке страницы.

2020-09-01 08:27 UTC, DEADushka108 commented on src/components/filter.js
> +    this._currenFilterType = FilterType.ALL;
Тоже рудимент

2020-09-01 08:59 UTC, DEADushka108 commented on src/presenter/movie-list.js
> +    this._filmsList = null;
тоже рудимент

2020-09-01 10:11 UTC, DEADushka108 commented on src/components/film-details.js
> +export default class FilmDetails extends AbstractSmartComponent {
не углядел лишний при решении конфликтов. Удалил лишний.

2020-09-01 11:22 UTC, Shv-sergey70 commented on src/components/film-details-new-comment.js
> +  _inputChangeHandler(evt) {
Глянь самое последнее предложение
https://github.com/htmlacademy-ecmascript/1146763-cinemaddict-12/pull/10#discussion_r480874120

2020-09-01 11:23 UTC, Shv-sergey70 commented on src/components/film-list-container.js
> +export default class FilmListContainer extends AbstractComponent {
Окей

2020-09-01 11:49 UTC, Shv-sergey70 requested changes

2020-09-01 11:49 UTC, Shv-sergey70 commented on src/components/show-more-btn.js
> +export default class ShowMoreButton extends AbstractComponent {
Верно, но еще надо название файла поменять

2020-09-01 11:49 UTC, Shv-sergey70 commented on src/components/user-title.js
> +    return createUserTitleTemplate(this._title);
Класс небольшой, можно сразу здесь писать разметку.
P.S вообще выносить разметку вне класса стоит только тогда, когда она действительно большая и неудобно будет просматривать код класса. То есть (20+ строк). В таких же случаях можно все совмещать

2020-09-01 11:49 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +const renderFilms = (filmsListContainer, films, onDataChange, onViewChange, onCommentsChange, api, commentsModel) => {
Если метод разместить в классе, то не придется передавать кучу параметров, так как все будет доступно через `this`

2020-09-01 11:49 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +const siteHeaderElement = document.querySelector(`.header`);
Так делать по-прежнему нельзя. Если компонент ранга не входит в ответственность текущего презентера (если этот компонент не входит в контейнер презентера), то не нужно его здесь и создавать

2020-09-01 11:49 UTC, Shv-sergey70 commented on src/presenter/movie-card.js
> +      evt.target.checked = !evt.target.checked ? evt.target.value : false;
А зачем это делать? Там же инпуты, а значит они сами переключатся в состояние checked и наоборот

2020-09-01 11:49 UTC, Shv-sergey70 commented on src/presenter/movie-card.js
> +    this._filmDetailsControlsComponent.setAddToWatchlistHandler((evt) => {
Обработчики, которые ты навешиваешь на кнопки попапа очень похожи на обработчики карточки. Попробуй вынести их в приватные методы класса и добавлять их в обоих местах

2020-09-01 11:49 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +  _onCommentsChange(filmPresenter, oldData, newData, film) {
А зачем этот метод размещать здесь? Почему не в презентере самого фильма?

2020-09-01 11:49 UTC, Shv-sergey70 commented on src/presenter/movie-card.js
> +    }, SHAKE_ANIMATION_TIMEOUT);
Все это содержимое относится к поведению вью попапа. Так что этот код стоит разместить в методе попапа и из презентера вызывать лишь его

2020-09-01 11:49 UTC, Shv-sergey70 commented on src/presenter/movie-card.js
> +  }
Тут аналогично тому, что я писал выше

2020-09-03 05:06 UTC, Shv-sergey70 commented on src/presenter/movie-card.js
> +      });
Было бы хорошо создать функцию-обработчик, которую ты передаешь в `setDeleteButtonHandler` как приватный метод класса. Чтобы каждый раз при отрисовке комментариев не создавать функцию в памяти заново

2020-09-03 05:06 UTC, Shv-sergey70 commented on src/presenter/movie-card.js
> +        if (this._mode === Mode.OPEN) {
А зачем эта проверка здесь?

2020-09-03 05:06 UTC, merged