Module9 task1
htmlacademy-ecmascript/1146763-cinemaddict-12 pull request #11
Opened 2020-09-03 10:06 UTC by DEADushka108

2020-09-04 08:00 UTC, Shv-sergey70 requested changes

2020-09-04 08:00 UTC, Shv-sergey70 commented on src/api/provider.js
> +};
А зачем тебе делать эти манипуляции? Ты смотрел что приходит на 78 строке в `response`?

2020-09-04 11:26 UTC, Shv-sergey70 commented on src/api/provider.js
> +          const items = this._createStoreStructure(updatedFilms);
`const items = this._createStoreStructure(response.updated)`

2020-09-04 14:13 UTC, DEADushka108 commented on src/api/provider.js
> +          const items = this._createStoreStructure(updatedFilms);
Почему то не работает. И кеш чистил и браузеры другие открывал(Скорее всего руки не оттуда растут)

2020-09-05 06:49 UTC, Shv-sergey70 approved these changes
Задание принимаю. Но нужно сделать эту логику:
https://github.com/htmlacademy-ecmascript/taskmanager-12/pull/12/files#diff-1c90ff38a08209f9ebd4d05d1e43358eR87-R94

Так как сейчас, если я отключу интернет, то в интерфейсе тайтл не поменяется. И синхронизация при появлении интернета не произойдет

2020-09-05 06:49 UTC, merged