Личный проект: меняй-удаляй (часть 1)
htmlacademy-ecmascript/1146763-cinemaddict-12 pull request #8
Opened 2020-08-26 11:10 UTC by DEADushka108

2020-08-26 15:49 UTC, Shv-sergey70 requested changes
При нажатии кнопок в попапе в карточке они не отражаются. То есть не синхронизовано

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/components/card-controls.js
> +  const {isInWatchlist, isInHistory, isInFavorites} = options;
Можно сразу так деструктурировать:
```
const createControlsTemplate = ({isInWatchlist, isInHistory, isInFavorites}) => {
```

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/components/comments.js
> +  return comments.map((comment) => {
`comment` прямо тут стоит деструктурировать

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/components/filters.js
> +    ${filter.name} ${(index > 0 && filter.count <= MAX_FILTER_COUNT) ? `<span class="main-navigation__item-count">${filter.count}</span>` : ``}
Зачем это `filter.count <= MAX_FILTER_COUNT` условие?

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/components/filters.js
> +        const filterName = evt.target.tagName === `A` ? evt.target.getAttribute(`href`) : evt.target.parentElement.getAttribute(`href`);
`getAttribute('href')` -> лучше все же использовать data атрибут для определения типа фильтра, так как у href иное назначение

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/components/filters.js
> +      return;
Можно этот `return` не писать

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/components/site-navigation.js
> +  }
Разметка небольшая, можно сразу так:
```
  getTemplate() {
    return `<nav class="main-navigation">
      <a href="#stats" class="main-navigation__additional">Stats</a>
    </nav>`;
  }
```

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/mock/film-cards.js
> +};
используй короткий синтаксис

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/presenter/movie-filter.js
> +    });
Также используй короткий синтаксис

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/utils/filters.js
> +};
используй короткий синтаксис

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/utils/render.js
>    * @param {string} component
string -> AbstractComponent ?

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/main.js
> +filterPresenter.render();
Если у класса нужно вызвать только 1 метод, то сразу так:

```
new FilterPresenter(siteNavigationComponent.getElement(), filmsModel).render();
```

2020-08-26 15:49 UTC, Shv-sergey70 commented on src/presenter/movie-comments.js
> +      return;
return нужен?

2020-08-27 03:14 UTC, DEADushka108 commented on src/components/filters.js
> +    ${filter.name} ${(index > 0 && filter.count <= MAX_FILTER_COUNT) ? `<span class="main-navigation__item-count">${filter.count}</span>` : ``}
По ТЗ п.1.6: Количество фильмов, соответствующих фильтру отображается справа в элементе с фильтром. Для фильтра «All movies» количество не отображается. Если фильтру соответствует больше 5 фильмов, действуют правила отображения как для списка фильмов «All movies». 
Это если я правильно понял.

2020-08-27 05:48 UTC, Shv-sergey70 commented on src/components/filters.js
> +    ${filter.name} ${(index > 0 && filter.count <= MAX_FILTER_COUNT) ? `<span class="main-navigation__item-count">${filter.count}</span>` : ``}
Похоже на то, странно конечно это. Уточни у куратора этот момент лучше на всякий случай

2020-08-27 05:51 UTC, Shv-sergey70 commented on src/presenter/movie-filter.js
> +
```
const createFilter = (filter, films, checkedFilter) => ({
  name: filter,
  count: getFiltredFilms(films, filter).length,
  isChecked: filter === checkedFilter,
});
```

2020-08-27 05:51 UTC, merged